// console.log("Hello js:");
// let a ;
// console.log(a);
// a = 10
// console.log(a);
// a = "string"
// console.log(a);
/*      primitive data types in js */
// 1)String 
let a = "Hello World!";
console.log(a);


// 2) Number it is like int/float (can be convertertable ) data type in c , c++ , java 
let b = 10;
let c = 10.5;
console.log(b);
console.log(c);



// 3) Boolean TRUE / FALSE
let d = true;
console.log(d);



// 4) undefined anything which is not defined in js is undefined 
let e;
console.log(e);


// 5) null it is defined but contain nothing 
let f = null;
console.log(f);